function [fitresult_fol_1, gof] = createFit_fol_1(frequency, alpha_fol_1)
%CREATEFIT(FREQUENCY,ALPHA_FOL_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: frequency
%      Y Output: alpha_fol_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Jan-2026 09:58:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frequency, alpha_fol_1 );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult_fol_1, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult_fol_1, xData, yData );
legend( h, 'alpha_fol_1 vs. frequency', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'frequency', 'Interpreter', 'none' );
ylabel( 'alpha_fol_1', 'Interpreter', 'none' );
grid on


