function [fitresult, gof] = createFit_atm(frequency, alpha)
%CREATEFIT(FREQUENCY,ALPHA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: frequency
%      Y Output: alpha
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2026 08:41:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frequency, alpha );

% Set up fittype and options.
ft = fittype( 'poly5' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'alpha vs. frequency', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'frequency', 'Interpreter', 'none' );
ylabel( 'alpha', 'Interpreter', 'none' );
grid on


