function [fitresult, gof] = createFit_grd(frequency_iso, Agr)
%CREATEFIT(FREQUENCY_ISO,AGR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: frequency_iso
%      Y Output: Agr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jan-2026 09:50:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frequency_iso, Agr );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Agr vs. frequency_iso', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'frequency_iso', 'Interpreter', 'none' );
ylabel( 'Agr', 'Interpreter', 'none' );
grid on


