function [fitresult_fol, gof] = createFit_foliage(frequency, alpha)
%CREATEFIT(FREQUENCY,ALPHA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: frequency
%      Y Output: alpha
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Jan-2026 13:09:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frequency, alpha );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0.078355167232737 0.198434027442839 -0.00300144746208542 -3.98477248505909];

% Fit model to data.
[fitresult_fol, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult_fol, xData, yData );
legend( h, 'alpha vs. frequency', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'frequency', 'Interpreter', 'none' );
ylabel( 'alpha', 'Interpreter', 'none' );
grid on


