import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
from tkinter import filedialog # Needed for the save/load dialogs
import numpy as np
import pandas as pd # Needed to easily export/import the data to CSV

import matplotlib
matplotlib.use('TkAgg')
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.widgets import Cursor # Added for crosshairs

from acoustics_core import JetAcousticsSolver

try:
    from PIL import Image, ImageTk
except ImportError:
    pass

class JetAcousticsGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Jet Acoustics Simulator ")
        self.root.geometry("1450x950")
        
        # --- CUSTOM WHITE & CHERRY RED THEME SETUP ---
        self.bg_color = "#FFFFFF"       
        self.frame_color = "#F8F9FA"    
        self.text_color = "#212529"     
        self.cherry_red = "#D2042D"     
        self.btn_color = self.cherry_red      
        
        self.root.configure(bg=self.bg_color)
        
        style = ttk.Style()
        style.theme_use('clam')
        style.configure("TFrame", background=self.bg_color)
        style.configure("TLabelframe", background=self.bg_color, bordercolor="#DEE2E6")
        style.configure("TLabelframe.Label", background=self.bg_color, font=("Arial", 10, "bold"), foreground=self.cherry_red)
        style.configure("TLabel", background=self.bg_color, font=("Arial", 10), foreground=self.text_color)
        
        style.configure("TNotebook", background=self.bg_color, borderwidth=0)
        style.configure("TNotebook.Tab", background="#E9ECEF", font=("Arial", 11, "bold"), padding=[15, 8], foreground="#495057", borderwidth=0)
        style.map("TNotebook.Tab", background=[("selected", self.cherry_red)], foreground=[("selected", "white")])
        
        # Treeview (Data Table) Styling
        style.configure("Treeview", font=("Arial", 10), rowheight=25)
        style.configure("Treeview.Heading", font=("Arial", 11, "bold"), background=self.frame_color, foreground=self.text_color)

        self.solver = JetAcousticsSolver()
        
        # Store latest data for exporting
        self.latest_df = None 

        self._build_welcome_page()

    def _build_welcome_page(self):
        self.welcome_frame = tk.Frame(self.root, bg=self.bg_color)
        self.welcome_frame.pack(fill=tk.BOTH, expand=True)

        inner_frame = tk.Frame(self.welcome_frame, bg=self.bg_color)
        inner_frame.place(relx=0.5, rely=0.5, anchor="center")

        left_col = tk.Frame(inner_frame, bg=self.bg_color)
        left_col.pack(side=tk.LEFT, padx=(0, 50))
        
        right_col = tk.Frame(inner_frame, bg=self.bg_color)
        right_col.pack(side=tk.RIGHT)

        tk.Label(left_col, text="JET ACOUSTICS SIMULATOR", font=("Arial", 36, "bold"), bg=self.bg_color, fg=self.text_color).pack(anchor="w")
        tk.Label(left_col, text="ACOUSTICS PREDICTION TOOL", font=("Arial", 14, "bold"), bg=self.bg_color, fg=self.cherry_red).pack(anchor="w", pady=(0, 15))

        tk.Frame(left_col, height=3, width=100, bg=self.cherry_red).pack(anchor="w", pady=(0, 30))

        desc_text = (
            "This code calculates the Sound Pressure Level (SPL) and Overall Sound Pressure Level (OASPL)\n"
            "generated by rocket engine exhausts. Built upon the NASA Distributed Source Method (DSM-2),\n"
            "the exhaust plume is divided into discrete noise sources and the empirical directivity \n"
            "corrections are applied based on Strouhal numbers to predict acoustic loading at critical distances."
        )
        tk.Label(left_col, text=desc_text, font=("Arial", 12), bg=self.bg_color, fg="#495057", justify="left").pack(anchor="w", pady=(0, 40))

        inst_frame = tk.Frame(left_col, bg=self.frame_color, padx=40, pady=25, highlightbackground="#DEE2E6", highlightthickness=1)
        inst_frame.pack(anchor="w", pady=(0, 40), fill=tk.X)

        tk.Label(inst_frame, text="WORKFLOW INSTRUCTIONS", font=("Arial", 11, "bold"), bg=self.frame_color, fg=self.cherry_red).pack(anchor="w", pady=(0, 10))
        
        instructions = [
            "• Initialize test configuration (Undeflected or Deflected jet) via the primary workspace tabs.",
            "• Define Engine parameters, including Engine Thrust, Exit Velocity, and Mach number.",
            "• Establish spatial geometry by entering the measurement coordinates (X, Y, Z) for the microphone array.",
            "• View the live 3D Empirical Directivity RBF mapping in its dedicated tab.",
            "• Execute the simulation to render SPL spectra, OASPL plots, and exportable data tables."
        ]
        for inst in instructions:
            tk.Label(inst_frame, text=inst, font=("Arial", 11), bg=self.frame_color, fg=self.text_color).pack(anchor="w", pady=4)

        start_btn = tk.Button(left_col, text="INITIALIZE WORKSPACE ➔", bg=self.cherry_red, fg="white", font=("Arial", 12, "bold"), relief="flat", padx=30, pady=12, command=self._launch_main_app)
        start_btn.pack(anchor="w", pady=(0, 10))
        
        tk.Label(left_col, text="Version 1.1 | JATO Validation", font=("Arial", 9), bg=self.bg_color, fg="#ADB5BD").pack(anchor="w")

        try:
            img = Image.open("dsm_diagram.png")
            target_width = 550
            target_height = int(target_width * img.height / img.width)
            try: resample_filter = Image.Resampling.LANCZOS
            except AttributeError: resample_filter = Image.ANTIALIAS
            img = img.resize((target_width, target_height), resample_filter)
            self.welcome_img = ImageTk.PhotoImage(img)
            img_label = tk.Label(right_col, image=self.welcome_img, bg=self.bg_color)
            img_label.pack()
        except Exception:
            pass

    def _launch_main_app(self):
        self.welcome_frame.destroy()

        self.left_panel = tk.Frame(self.root, width=450, bg=self.bg_color)
        self.left_panel.pack(side=tk.LEFT, fill=tk.Y, padx=15, pady=15)
        
        ttk.Separator(self.root, orient='vertical').pack(side=tk.LEFT, fill=tk.Y, pady=20)
        
        self.right_panel = tk.Frame(self.root, bg=self.bg_color)
        self.right_panel.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True, padx=15, pady=15)

        self._build_input_sections()
        self._build_plot_section()
        self._plot_static_3d_surface()

    def _build_input_sections(self):
        self.notebook = ttk.Notebook(self.left_panel)
        self.notebook.pack(fill=tk.X, pady=(0, 10))

        # --- TAB 1: UNDEFLECTED ---
        self.tab_undef = ttk.Frame(self.notebook)
        self.notebook.add(self.tab_undef, text=" UNDEFLECTED JET ")
        self.entries_un = {}
        params_un = [
            ("Number of Engines", "1"),
            ("Thrust per Engine (N)", "4537.18"),
            ("Exit Velocity (m/s)", "1277.74"),
            ("Exit Mach Number", "2.485"),
            ("Exit Diameter (m)", "0.066"),
            ("Efficiency", "1")
        ]
        un_frame = ttk.LabelFrame(self.tab_undef, text="Engine Parameters", padding=(10, 10))
        un_frame.pack(fill=tk.X, pady=10, padx=5)
        self._create_form(un_frame, params_un, self.entries_un)

        # --- TAB 2: DEFLECTED ---
        self.tab_def = ttk.Frame(self.notebook)
        self.notebook.add(self.tab_def, text=" DEFLECTED JET ")
        self.entries_def = {}
        params_def_eng = [
            ("Number of Engines", "1"),
            ("Thrust per Engine (N)", "4537.18"),
            ("Exit Velocity (m/s)", "1277.74"),
            ("Exit Mach Number", "2.485"),
            ("Exit Diameter (m)", "0.066"),
            ("Efficiency", "1")
        ]
        params_def_geo = [
            ("Impingement Point (m)", "15.0"),
            ("Uplift Angle (deg)", "45.0")
        ]
        def_frame_eng = ttk.LabelFrame(self.tab_def, text="Engine Parameters", padding=(10, 10))
        def_frame_eng.pack(fill=tk.X, pady=5, padx=5)
        self._create_form(def_frame_eng, params_def_eng, self.entries_def)
        
        def_frame_geo = ttk.LabelFrame(self.tab_def, text="Test Stand Geometry", padding=(10, 10))
        def_frame_geo.pack(fill=tk.X, pady=5, padx=5)
        self._create_form(def_frame_geo, params_def_geo, self.entries_def)

        # --- TAB 3: FREQUENCY SETTINGS ---
        self.tab_freq = ttk.Frame(self.notebook)
        self.notebook.add(self.tab_freq, text=" FREQUENCY BANDS ")
        self.entries_freq = {}
        params_freq = [
            ("Lower Frequency (Hz)", "75.0"),
            ("Octave Band (n for 1/n)", "1"),
            ("Number of Frequencies", "7")
        ]
        freq_frame = ttk.LabelFrame(self.tab_freq, text="Spectrum Band Parameters", padding=(10, 10))
        freq_frame.pack(fill=tk.X, pady=10, padx=5)
        self._create_form(freq_frame, params_freq, self.entries_freq)
        
        ttk.Label(self.tab_freq, text="Engineering Notes:\n• Standard Undeflected uses n=1, nf=7.\n• Standard Deflected uses n=3, nf=24.", foreground="#6C757D").pack(padx=5, pady=5, anchor="w")

        # --- SHARED: MIC COORDINATES ---
        self.mic_frame = ttk.LabelFrame(self.left_panel, text="Microphone Coordinates (m)", padding=(5, 5))
        self.mic_frame.pack(fill=tk.X, pady=5)

        btn_frame = ttk.Frame(self.mic_frame)
        btn_frame.pack(side=tk.BOTTOM, fill=tk.X, pady=(5, 0))
        tk.Button(btn_frame, text="+ Add Mic", bg="#E9ECEF", fg=self.text_color, font=("Arial", 9), relief="flat", command=lambda: self._add_mic_row(0.0, 0.0, 0.0)).pack(side=tk.LEFT, padx=(5, 5))
        tk.Button(btn_frame, text="- Remove", bg="#E9ECEF", fg=self.text_color, font=("Arial", 9), relief="flat", command=self._remove_mic_row).pack(side=tk.LEFT)

        self.mic_canvas = tk.Canvas(self.mic_frame, bg=self.bg_color, highlightthickness=0, height=140) 
        self.mic_scrollbar = ttk.Scrollbar(self.mic_frame, orient="vertical", command=self.mic_canvas.yview)
        
        self.mic_inner_frame = ttk.Frame(self.mic_canvas)
        self.mic_inner_frame.bind("<Configure>", lambda e: self.mic_canvas.configure(scrollregion=self.mic_canvas.bbox("all")))
        
        self.mic_canvas.create_window((0, 0), window=self.mic_inner_frame, anchor="nw")
        self.mic_canvas.configure(yscrollcommand=self.mic_scrollbar.set)
        
        self.mic_canvas.pack(side=tk.LEFT, fill=tk.X, expand=True)
        self.mic_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        ttk.Label(self.mic_inner_frame, text="Mic", font=("Arial", 10, "bold"), width=5).grid(row=0, column=0, padx=2, pady=2)
        ttk.Label(self.mic_inner_frame, text="X", font=("Arial", 10, "bold"), width=8).grid(row=0, column=1, padx=2, pady=2)
        ttk.Label(self.mic_inner_frame, text="Y", font=("Arial", 10, "bold"), width=8).grid(row=0, column=2, padx=2, pady=2)
        ttk.Label(self.mic_inner_frame, text="Z", font=("Arial", 10, "bold"), width=8).grid(row=0, column=3, padx=2, pady=2)

        self.mic_entries = []
        default_mics = [
            (0.133, 0, 0.33), (0.133, 0, 0.66), (0.133, 0, 0.99),
            (0.133, 0, 1.32), (0.133, 0, 1.98)
        ]
        for x, y, z in default_mics:
            self._add_mic_row(x, y, z)

        # --- SHARED: PLOT FORMATTING ---
        plot_frame = ttk.LabelFrame(self.left_panel, text="Plot Formatting & Validation", padding=(10, 10))
        plot_frame.pack(fill=tk.X, pady=5)

        ttk.Label(plot_frame, text="Font Family:").grid(row=0, column=0, sticky="w", pady=5)
        self.font_var = tk.StringVar(value="Times New Roman")
        ttk.Combobox(plot_frame, textvariable=self.font_var, values=["Times New Roman", "Arial", "Courier New", "Helvetica"], width=15).grid(row=0, column=1, sticky="ew", pady=5)

        ttk.Label(plot_frame, text="Line Style:").grid(row=1, column=0, sticky="w", pady=5)
        self.line_var = tk.StringVar(value="-")
        ttk.Combobox(plot_frame, textvariable=self.line_var, values=["-", "--", "-.", ":"], width=15).grid(row=1, column=1, sticky="ew", pady=5)

        ttk.Label(plot_frame, text="Line Width:").grid(row=2, column=0, sticky="w", pady=5)
        self.width_var = tk.StringVar(value="2.0")
        ttk.Combobox(plot_frame, textvariable=self.width_var, values=["1.0", "1.5", "2.0", "2.5", "3.0"], width=15).grid(row=2, column=1, sticky="ew", pady=5)

        ttk.Label(plot_frame, text="Mics to Plot (OASPL):").grid(row=3, column=0, sticky="w", pady=5)
        self.mics_plot_var = tk.StringVar(value="All")
        ttk.Entry(plot_frame, textvariable=self.mics_plot_var, width=15).grid(row=3, column=1, sticky="ew", pady=5)

        # --- NEW: EXPERIMENTAL CSV LOADING ---
        ttk.Label(plot_frame, text="Validation CSV:").grid(row=4, column=0, sticky="w", pady=5)
        csv_subframe = ttk.Frame(plot_frame)
        csv_subframe.grid(row=4, column=1, sticky="ew", pady=5)
        
        self.csv_var = tk.StringVar()
        ttk.Entry(csv_subframe, textvariable=self.csv_var, width=10).pack(side=tk.LEFT, fill=tk.X, expand=True)
        
        def _browse_csv():
            f = filedialog.askopenfilename(filetypes=[("CSV Files", "*.csv"), ("All Files", "*.*")])
            if f: self.csv_var.set(f)
            
        tk.Button(csv_subframe, text="📁", command=_browse_csv, bg="#E9ECEF", relief="flat", padx=3).pack(side=tk.RIGHT, padx=(5,0))

        self.run_btn = tk.Button(self.left_panel, text="▶ RUN SIMULATION", bg=self.btn_color, fg="white", font=("Arial", 12, "bold"), relief="flat", command=self.run_calculation)
        self.run_btn.pack(side=tk.BOTTOM, fill=tk.X, pady=(10, 20), ipady=8)

    def _create_form(self, parent_frame, param_list, dict_ref):
        for i, (label_text, default_val) in enumerate(param_list):
            ttk.Label(parent_frame, text=label_text).grid(row=i, column=0, sticky="w", pady=4)
            entry_var = tk.StringVar(value=default_val)
            entry = ttk.Entry(parent_frame, textvariable=entry_var, justify="right", width=12)
            entry.grid(row=i, column=1, sticky="e", padx=5, pady=4)
            dict_ref[label_text] = entry_var

    def _add_mic_row(self, x_val, y_val, z_val):
        row_idx = len(self.mic_entries) + 1 
        lbl = ttk.Label(self.mic_inner_frame, text=f"#{row_idx}", width=5)
        lbl.grid(row=row_idx, column=0, padx=2, pady=2)
        
        x_var, y_var, z_var = tk.StringVar(value=str(x_val)), tk.StringVar(value=str(y_val)), tk.StringVar(value=str(z_val))
        
        x_ent = ttk.Entry(self.mic_inner_frame, textvariable=x_var, width=8, justify="center")
        x_ent.grid(row=row_idx, column=1, padx=2, pady=2)
        y_ent = ttk.Entry(self.mic_inner_frame, textvariable=y_var, width=8, justify="center")
        y_ent.grid(row=row_idx, column=2, padx=2, pady=2)
        z_ent = ttk.Entry(self.mic_inner_frame, textvariable=z_var, width=8, justify="center")
        z_ent.grid(row=row_idx, column=3, padx=2, pady=2)
        
        self.mic_entries.append({
            "label": lbl, "x_ent": x_ent, "y_ent": y_ent, "z_ent": z_ent,
            "x_var": x_var, "y_var": y_var, "z_var": z_var
        })
        self.mic_canvas.update_idletasks()
        self.mic_canvas.yview_moveto(1.0)

    def _remove_mic_row(self):
        if len(self.mic_entries) > 1: 
            last_mic = self.mic_entries.pop()
            for key in ["label", "x_ent", "y_ent", "z_ent"]:
                last_mic[key].destroy()

    def _build_plot_section(self):
        self.viz_notebook = ttk.Notebook(self.right_panel)
        self.viz_notebook.pack(fill=tk.BOTH, expand=True)

        # VIZ TAB 1: 3D Surface
        self.vtab_3d = ttk.Frame(self.viz_notebook)
        self.viz_notebook.add(self.vtab_3d, text=" 3D RBF Surface ")
        self.fig_3d = Figure(figsize=(8, 8), dpi=100)
        self.ax3d = self.fig_3d.add_subplot(111, projection='3d')
        self.canvas_3d = FigureCanvasTkAgg(self.fig_3d, master=self.vtab_3d)
        self.canvas_3d.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)
        NavigationToolbar2Tk(self.canvas_3d, self.vtab_3d).config(background=self.bg_color)

        # VIZ TAB 2: SPL Spectrum
        self.vtab_spec = ttk.Frame(self.viz_notebook)
        self.viz_notebook.add(self.vtab_spec, text=" SPL Spectrum ")
        self.fig_spec = Figure(figsize=(8, 8), dpi=100)
        self.fig_spec.patch.set_facecolor(self.bg_color)
        self.ax_spec = self.fig_spec.add_subplot(111)
        self.ax_spec.grid(True, linestyle=":", alpha=0.6)
        self.canvas_spec = FigureCanvasTkAgg(self.fig_spec, master=self.vtab_spec)
        self.canvas_spec.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)
        NavigationToolbar2Tk(self.canvas_spec, self.vtab_spec).config(background=self.bg_color)
        
        # Add Crosshair to Spectrum
        self.cursor_spec = Cursor(self.ax_spec, useblit=True, color='red', linewidth=1, linestyle='--')

        # VIZ TAB 3: OASPL Profile
        self.vtab_oaspl = ttk.Frame(self.viz_notebook)
        self.viz_notebook.add(self.vtab_oaspl, text=" OASPL Profile ")
        self.fig_oaspl = Figure(figsize=(8, 8), dpi=100)
        self.fig_oaspl.patch.set_facecolor(self.bg_color)
        self.ax_oaspl = self.fig_oaspl.add_subplot(111)
        self.ax_oaspl.grid(True, linestyle=":", alpha=0.6)
        self.canvas_oaspl = FigureCanvasTkAgg(self.fig_oaspl, master=self.vtab_oaspl)
        self.canvas_oaspl.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)
        NavigationToolbar2Tk(self.canvas_oaspl, self.vtab_oaspl).config(background=self.bg_color)
        
        # Add Crosshair to OASPL
        self.cursor_oaspl = Cursor(self.ax_oaspl, useblit=True, color='red', linewidth=1, linestyle='--')

        # --- VIZ TAB 4: DATA TABLE EXPORT ---
        self.vtab_data = ttk.Frame(self.viz_notebook)
        self.viz_notebook.add(self.vtab_data, text=" Data Export ")
        
        # Header for the table tab
        header_frame = tk.Frame(self.vtab_data, bg=self.bg_color, pady=10, padx=10)
        header_frame.pack(fill=tk.X)
        tk.Label(header_frame, text="Calculated Acoustic Data (SPL & OASPL)", font=("Arial", 16, "bold"), bg=self.bg_color, fg=self.text_color).pack(side=tk.LEFT)
        
        self.export_btn = tk.Button(header_frame, text="Download CSV", bg="#28A745", fg="white", font=("Arial", 11, "bold"), relief="flat", padx=15, command=self._export_to_csv)
        self.export_btn.pack(side=tk.RIGHT)
        
        # The actual Treeview table
        table_frame = tk.Frame(self.vtab_data)
        table_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        
        self.tree_scroll_y = ttk.Scrollbar(table_frame, orient="vertical")
        self.tree_scroll_y.pack(side=tk.RIGHT, fill=tk.Y)
        self.tree_scroll_x = ttk.Scrollbar(table_frame, orient="horizontal")
        self.tree_scroll_x.pack(side=tk.BOTTOM, fill=tk.X)
        
        self.data_tree = ttk.Treeview(table_frame, yscrollcommand=self.tree_scroll_y.set, xscrollcommand=self.tree_scroll_x.set)
        self.data_tree.pack(fill=tk.BOTH, expand=True)
        self.tree_scroll_y.config(command=self.data_tree.yview)
        self.tree_scroll_x.config(command=self.data_tree.xview)

    def _plot_static_3d_surface(self):
        deg, strn, di = self.solver.deg, self.solver.strn, self.solver.di
        deg_grid = np.linspace(deg.min(), deg.max(), 40)
        strn_grid = np.linspace(strn.min(), strn.max(), 40)
        D_mesh, S_mesh = np.meshgrid(deg_grid, strn_grid)
        
        grid_points_scaled = self.solver.scaler.transform(np.column_stack((D_mesh.ravel(), S_mesh.ravel())))
        DI_pred = self.solver.rbf_smooth(grid_points_scaled[:, 0], grid_points_scaled[:, 1]).reshape(D_mesh.shape)
        
        self.ax3d.plot_surface(D_mesh, S_mesh, DI_pred, cmap='Blues_r', alpha=0.75, edgecolor='black', linewidth=0.1, rcount=30, ccount=30)
        self.ax3d.scatter(deg, strn, di, color='black', marker='d', s=10, depthshade=False, label='Empirical Data')
        
        self.ax3d.set_xlabel('Angle (deg)', fontsize=11, fontname="Arial")
        self.ax3d.set_ylabel('Strouhal Number', fontsize=11, fontname="Arial")
        self.ax3d.set_zlabel('Directivity Index (dB)', fontsize=11, fontname="Arial")
        self.ax3d.set_title("RBF Directivity Surface Fitting", fontsize=16, fontweight='bold', fontname="Arial", color=self.text_color)
        
        self.ax3d.view_init(elev=20, azim=-125)
        self.ax3d.set_zlim(di.min() - 5, di.max() + 5)
        
        self.ax3d.set_facecolor(self.bg_color)
        
        for pane in [self.ax3d.xaxis, self.ax3d.yaxis, self.ax3d.zaxis]:
            pane.set_pane_color((0.95, 0.95, 0.95, 1.0))
        self.canvas_3d.draw()

    def _update_data_table(self, f_signal, SPLbp, OASPL):
        self.data_tree.delete(*self.data_tree.get_children())
        
        num_mics = len(OASPL)
        columns = ["Frequency (Hz)"] + [f"Mic {i+1} SPL (dB)" for i in range(num_mics)]
        
        self.data_tree["columns"] = columns
        self.data_tree.column("#0", width=0, stretch=tk.NO) 
        self.data_tree.heading("#0", text="")
        
        for col in columns:
            self.data_tree.column(col, anchor=tk.CENTER, width=120)
            self.data_tree.heading(col, text=col)
            
        rows = []
        for j in range(len(f_signal)):
            row = [f"{f_signal[j]:.2f}"] + [f"{SPLbp[j, i]:.2f}" for i in range(num_mics)]
            self.data_tree.insert("", tk.END, values=row)
            rows.append(row)
            
        oaspl_row = ["OASPL (dB)"] + [f"{OASPL[i]:.2f}" for i in range(num_mics)]
        self.data_tree.insert("", tk.END, values=[""] * len(columns))
        self.data_tree.insert("", tk.END, values=oaspl_row, tags=('bold_row',))
        self.data_tree.tag_configure('bold_row', font=("Arial", 10, "bold"), background="#E9ECEF")
        rows.append([""] * len(columns))
        rows.append(oaspl_row)

        self.latest_df = pd.DataFrame(rows, columns=columns)

    def _export_to_csv(self):
        if self.latest_df is None:
            messagebox.showwarning("No Data", "Please run the simulation first before exporting data.")
            return
            
        file_path = filedialog.asksaveasfilename(
            defaultextension=".csv",
            filetypes=[("CSV Files", "*.csv"), ("All Files", "*.*")],
            title="Save Acoustic Data"
        )
        if file_path:
            try:
                self.latest_df.to_csv(file_path, index=False)
                messagebox.showinfo("Export Successful", f"Data successfully saved to:\n{file_path}")
            except Exception as e:
                messagebox.showerror("Export Failed", f"Could not save file:\n{str(e)}")

    def run_calculation(self):
        try:
            self.run_btn.config(text="CALCULATING...", bg="#f39c12")
            self.root.update()

            active_tab_index = self.notebook.index(self.notebook.select())
            is_deflected = (active_tab_index == 1)

            params = {key: float(var.get()) for key, var in (self.entries_def.items() if is_deflected else self.entries_un.items())}

            f_lower = float(self.entries_freq["Lower Frequency (Hz)"].get())
            n_oct = float(self.entries_freq["Octave Band (n for 1/n)"].get())
            nf = int(float(self.entries_freq["Number of Frequencies"].get()))

            mic_coords = []
            for mic in self.mic_entries:
                try:
                    mic_coords.append([float(mic["x_var"].get()), float(mic["y_var"].get()), float(mic["z_var"].get())])
                except ValueError:
                    raise ValueError("All microphone coordinates must be valid numbers.")
            
            mic_location = np.array(mic_coords)
            num_mics = mic_location.shape[0]

            if is_deflected:
                f_signal, SPLbp, SPLbp_average, OASPL = self.solver.solve_deflected(
                    n_eng=params["Number of Engines"], F=params["Thrust per Engine (N)"],
                    ue=params["Exit Velocity (m/s)"], me=params["Exit Mach Number"],
                    dei=params["Exit Diameter (m)"], eta=params["Efficiency"],
                    mic_location=mic_location, x2=params["Impingement Point (m)"],
                    angle=params["Uplift Angle (deg)"], f_lower=f_lower, n_oct=n_oct, nf=nf
                )
            else:
                f_signal, SPLbp, SPLbp_average, OASPL = self.solver.solve_undeflected(
                    n_eng=params["Number of Engines"], F=params["Thrust per Engine (N)"],
                    ue=params["Exit Velocity (m/s)"], me=params["Exit Mach Number"],
                    dei=params["Exit Diameter (m)"], eta=params["Efficiency"],
                    mic_location=mic_location, f_lower=f_lower, n_oct=n_oct, nf=nf
                )

            self._update_data_table(f_signal, SPLbp, OASPL)

            mics_input = self.mics_plot_var.get().strip().lower()
            if mics_input == "all" or mics_input == "":
                plot_indices = list(range(num_mics))
            else:
                try:
                    parts = [p.strip() for p in mics_input.split(',')]
                    plot_indices = [int(p) - 1 for p in parts if p.isdigit()]
                    plot_indices = [i for i in plot_indices if 0 <= i < num_mics]
                    if not plot_indices: plot_indices = list(range(num_mics))
                except Exception:
                    plot_indices = list(range(num_mics))

            self.ax_spec.clear()
            self.ax_oaspl.clear()
            
            plot_font = self.font_var.get()
            l_style = self.line_var.get()
            l_width = float(self.width_var.get())

            # =========================================================================
            # SPECTRUM: Calculated Data
            # =========================================================================
            self.ax_spec.plot(f_signal, SPLbp_average, label='Calculated Average SPL', 
                              marker='o', markersize=6, 
                              linestyle=l_style, linewidth=l_width, color=self.cherry_red)

            # --- NEW: OVERLAY EXPERIMENTAL CSV DATA ---
            csv_path = self.csv_var.get().strip()
            if csv_path:
                try:
                    exp_df = pd.read_csv(csv_path, header=None)
                    if exp_df.shape[1] >= 2:
                        f_exp = exp_df.iloc[:, 0].to_numpy()
                        spl_exp = exp_df.iloc[:, 1].to_numpy()
                        self.ax_spec.plot(f_exp, spl_exp, label='Experimental (Validation)', 
                                          color='blue', linestyle='--', marker='*', 
                                          markersize=8, linewidth=max(1.5, l_width-0.5))
                except Exception as e:
                    print(f"Warning: Could not load CSV data for overlay. {e}")
            # ------------------------------------------

            self.ax_spec.set_xscale('log')
            self.ax_spec.set_xlim(np.min(f_signal) * 0.8, np.max(f_signal) * 1.2)
            self.ax_spec.minorticks_on()
            self.ax_spec.tick_params(axis='both', which='major', labelsize=10, width=1.5, length=6, direction='in', top=True, right=True)
            self.ax_spec.grid(which='major', linestyle='-', linewidth='0.5', color='black', alpha=0.4)
            self.ax_spec.grid(which='minor', linestyle=':', linewidth='0.5', color='gray', alpha=0.2)
            
            self.ax_spec.set_xlabel('Frequency (Hz)', fontsize=12, fontname=plot_font, color=self.text_color)
            self.ax_spec.set_ylabel('SPL (dB)', fontsize=12, fontname=plot_font, color=self.text_color)
            self.ax_spec.set_title("Deflected Jet Spectrum" if is_deflected else "Undeflected Jet Spectrum", fontsize=14, fontweight='bold', fontname=plot_font, color=self.text_color)
            self.ax_spec.legend(loc='best', frameon=True, prop={'family': plot_font, 'size': 10})

            # =========================================================================
            # OASPL: Still plots individual microphones based on selection
            # =========================================================================
            selected_mic_labels = [f"Mic {i+1}" for i in plot_indices]
            selected_oaspl = [OASPL[i] for i in plot_indices]
            
            self.ax_oaspl.plot(selected_mic_labels, selected_oaspl, marker='D', color=self.btn_color, linestyle='-.', linewidth=l_width, markersize=8)
            
            self.ax_oaspl.set_xlabel('Microphone Array Element', fontsize=12, fontname=plot_font, color=self.text_color)
            self.ax_oaspl.set_ylabel('OASPL (dB)', fontsize=12, fontname=plot_font, color=self.text_color)
            self.ax_oaspl.set_title('Overall Sound Pressure Level (OASPL)', fontsize=14, fontweight='bold', fontname=plot_font, color=self.text_color)
            self.ax_oaspl.grid(True, linestyle='-', linewidth='0.5', color='black', alpha=0.4)

            for ax in [self.ax_spec, self.ax_oaspl]:
                for label in ax.get_xticklabels() + ax.get_yticklabels():
                    label.set_fontname(plot_font)

            self.cursor_spec = Cursor(self.ax_spec, useblit=True, color='red', linewidth=1, linestyle='--')
            self.cursor_oaspl = Cursor(self.ax_oaspl, useblit=True, color='red', linewidth=1, linestyle='--')

            self.canvas_spec.draw()
            self.canvas_oaspl.draw()
            
            self.run_btn.config(text="▶ RUN SIMULATION", bg=self.btn_color)
            self.viz_notebook.select(self.vtab_spec)

        except Exception as e:
            self.run_btn.config(text="▶ RUN SIMULATION", bg=self.btn_color)
            messagebox.showerror("Simulation Error", f"An error occurred during calculation:\n{str(e)}")

if __name__ == "__main__":
    root = tk.Tk()
    app = JetAcousticsGUI(root)
    root.mainloop()
